# Generated by Django 2.1.5 on 2019-03-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.IntegerField(blank=True, default=0)),
                ('first_name_EN', models.CharField(default='', max_length=50)),
                ('last_name_EN', models.CharField(default='', max_length=50)),
                ('first_name_TH', models.CharField(default='', max_length=50)),
                ('last_name_TH', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('role', models.CharField(default='', max_length=50)),
                ('bank_no', models.CharField(default='', max_length=50)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('tell_no', models.CharField(default='', max_length=50)),
                ('sick_quo', models.IntegerField(blank=True, default=0)),
                ('sick_remain', models.IntegerField(blank=True, default=0)),
                ('annual_quo', models.IntegerField(blank=True, default=0)),
                ('annual_remain', models.IntegerField(blank=True, default=0)),
                ('lwp_quo', models.IntegerField(blank=True, default=0)),
                ('lwp_remain', models.IntegerField(blank=True, default=0)),
                ('personal_quo', models.IntegerField(blank=True, default=0)),
                ('personal_remain', models.IntegerField(blank=True, default=0)),
                ('lfwos_quo', models.IntegerField(blank=True, default=0)),
                ('lfwos_remain', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
