# Generated by Django 2.1.5 on 2019-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='Staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='Place',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='Time',
        ),
        migrations.AddField(
            model_name='checkin',
            name='place',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
