# Generated by Django 2.1.5 on 2019-03-17 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20190316_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(default='', max_length=50)),
                ('leavestartdatetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('leaveenddatetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('leavestatus', models.CharField(default='', max_length=50)),
                ('leavecomment', models.CharField(default='', max_length=255)),
                ('approvedby', models.CharField(default='', max_length=50)),
                ('leavefile1', django_postgres_unlimited_varchar.UnlimitedCharField()),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
