# Generated by Django 2.1.5 on 2019-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20190317_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='leave_file1',
            field=models.ImageField(upload_to='test'),
        ),
    ]
