# Generated by Django 2.1.5 on 2019-03-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20190317_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=255)),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
