# Generated by Django 2.1.5 on 2019-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
