# Generated by Django 2.1.5 on 2019-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20190326_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
