# Generated by Django 2.1.5 on 2019-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20190326_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
