# Generated by Django 2.1.5 on 2019-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20190326_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
