# Generated by Django 2.1.5 on 2019-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20190326_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
