# Generated by Django 2.1.5 on 2019-03-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20190326_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='time',
        ),
        migrations.AddField(
            model_name='calendar',
            name='Hours',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='calendar',
            name='Minutes',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='calendar',
            name='Month',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
