# Generated by Django 2.1.5 on 2019-04-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20190331_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(default='', max_length=50)),
                ('Status', models.CharField(default='', max_length=50)),
                ('Comment', models.CharField(default='', max_length=50)),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
