# Generated by Django 2.1.5 on 2019-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20190403_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='MemberInProject',
            field=models.ManyToManyField(to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='staff',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
