# Generated by Django 2.1.5 on 2019-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20190404_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='Years',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
