# Generated by Django 2.1.5 on 2019-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_calendar_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
