# Generated by Django 2.1.5 on 2019-03-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='', max_length=50)),
                ('Time', models.CharField(default='', max_length=50)),
                ('Status', models.CharField(default='', max_length=50)),
                ('Place', models.CharField(default='', max_length=50)),
                ('Staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
