# Generated by Django 2.1.5 on 2019-03-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190316_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='Status',
            new_name='status',
        ),
    ]
