# Generated by Django 2.1.5 on 2019-03-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_leaveinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='approvedby',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='leavecomment',
            new_name='leave_comment',
        ),
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='leaveenddatetime',
            new_name='leave_end_datetime',
        ),
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='leavefile1',
            new_name='leave_file1',
        ),
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='leavestartdatetime',
            new_name='leave_start_datetime',
        ),
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='leavestatus',
            new_name='leave_status',
        ),
        migrations.RenameField(
            model_name='leaveinfo',
            old_name='leavetype',
            new_name='leave_type',
        ),
    ]
