# Generated by Django 2.1.5 on 2019-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20190326_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
