# Generated by Django 2.1.5 on 2019-04-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20190403_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='MemberInProject',
            field=models.ManyToManyField(default='', to='employee.Employee'),
        ),
    ]
