# Generated by Django 2.1.5 on 2019-04-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_auto_20190404_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='MemberInProject',
            field=models.ManyToManyField(to='employee.Employee'),
        ),
    ]
